modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod/issues"
[[mods]]
modId="bettermcdonaldsmod"
version="1.19.4-3.0.1"
displayName="Better McDonalds Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod"
logoFile="logo.png"
credits="Volwert123, RPorotos"
authors="simon_mc"
description='''
Many well-known McDonalds products have been added.
'''
[[dependencies.bettermcdonaldsmod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettermcdonaldsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
[modproperties.bettermcdonaldsmod]
    catalogueItemIcon="bettermcdonaldsmod:happy_meal"