modLoader="javafml"
loaderVersion="[47,)"
license="moritz_htk Software License Agreement (mSLA)"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod/issues"
[[mods]]
modId="bettermcdonaldsmod"
version="1.20.1-3.0.3"
displayName="Better McDonald's Mod"
updateJSONURL="https://github.com/simon-mc28/Better-McDonalds-Mod-Forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-mcdonalds-mod"
logoFile="logo.png"
credits="Volwert123, RPorotos"
authors="simon_mc"
description='''Many well-known McDonalds products have been added.'''
[[dependencies.bettermcdonaldsmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bettermcdonaldsmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[modproperties.bettermcdonaldsmod]
    catalogueItemIcon="bettermcdonaldsmod:happy_meal"